### ISSUE TITLE
photo of Session 179 

### ISSUE THREAD

**Issue by numb95** [tehlug/tehlug#29]
Photos of Session 179 needs  to copy from server to repo.
I add this issue to fix this in future :)

**Comment by numb95** [comment]
why this issue closed ?
does the session 179 photos moved to git repo?

**Comment by fayyazzadeh** [comment]
http://tehlug.org/photos/179/92_05_29.jpg

**Comment by numb95** [comment]
read the issue again. 
I said the photo of session 179 should copy from server to Github repo.
it's present on server but not in the git repo.
take a look at this [line](https://github.com/tehlug/tehlug/blob/35ad53b30a0b9a39facca8a9648f3e8ab3a6eb87/contents/entries/179.php#L22):
there is no 179 directory in photos and of course, there is no `92_05_29.jpg`

**Comment by fayyazzadeh** [comment]
ok

**Comment by rezakamalifard** [comment]
@behdad222, why you close this? Did you fix it, and it's ok now?

**Comment by behdad222** [comment]
به سایت جدید منتقل شده
