### ISSUE TITLE
تغییر ظاهر سایت

### ISSUE THREAD

**Issue by ahangarha** [tehlug/tehlug#37]
سلام

برنامه‌ای برای تغییر ظاهر سایت هست؟
احیانا ملاحظاتی وجود داره در این خصوص؟

**Comment by ashkang** [comment]
TehLUG's website is based on a very simple code base (PHP + HTML). It encourages people to actively participate in our community by means of contribution to this code base. Our preference is to not fiddle with this website for various reasons:

1) Changing the look and feel of website has little to no value for us. Tehran Linux Users Group is a non-profit organization and people watch that website to get their community news. The simpler the website, the better.

2) It's a long tradition in FLOSS community to rely upon homegrown technologies and simple solutions. If you take a look at most of the old FLOSS community project websites, you get to see their simplicity. This is for various reasons outside the scope of this conversation.

3) This change requires man-power for website maintenance. If this is important to you, you can propose a draft for change and contact TehLUG's board. You need to convince the board that your changes actually do have value for this community.

4) Current structure encourages community contribution. We use a simple stack, our editors and git. That's it. No fancy tools. No extra load times. Plain and simple. Our resources are limited.

Again, if this is such an important issue to you, it has to go through the board process.

**Comment by emilsedgh** [comment]
I haven't been a contributor to Tehlug for a long time. So I don't really have a voice in here. However, I disagree with Ashkan in here.
If you feel like changing the appearance of the website, go ahead. Send a pull request.

We probably would rather have the same architecture as contributing to it is really easy. But if you want to update the looks, that must be OK I guess.

**Comment by ahangarha** [comment]
I think some enhancement in client side would improve the site. I agree
that it shouldn't use a lot of resources and also there is no need for
fancy stuffs there.
But still I think the site can be improved without making it heavy and
unnecessarily​ fancy.
I am familiar with git. So once I am done, I will make a pull request.

Bests

**Comment by efazati** [comment]
یه ورژن قدیمی من و یکی از دوستان با 
bootstrap - staticsite python
درست کردم ولی نمیدونم چی شد که بیخیال اعمالش شدیم

https://github.com/efazati/tehlug
